### ISSUE TITLE
Way slow playback start

### ISSUE THREAD

**Issue by dvv** [ValdikSS/aceproxy#20]
Hi!

Setup:
```
$ uname -a
Linux tv 3.16.0-28-generic #38-Ubuntu SMP Fri Dec 12 17:38:37 UTC 2014 i686 i686 i686 GNU/Linux
```
in virtualbox under iron windows 7.

Vanilla setup (no VLC, but looks like it turns out it's irrelevant here) from master, engine started with: `acecmd = "acestreamengine --client-console --log-stderr --live-cache-type memory --live-cache-size 128000000"`

VLC client at third machine, starts after circa 40-50 seconds. Neither excess processor activity, nor excess network activity due to aceproxy seen.

Now with `acehost = '192.168.1.2'` where the IP is iron windows host, running ace_engine.exe.

Same VLC client, starts after circa 4 seconds (only buffering done, as prescipted, I believe).

Wonder what can be the causes?

TIA,
--Vladimir

**Comment by ValdikSS** [comment]
Can I close this?

**Comment by dvv** [comment]
Please do. I'll append once I have more data. Thanks
