### ISSUE TITLE
Aceproxy + Mips

### ISSUE THREAD

**Issue by jamescraig81** [ValdikSS/aceproxy#26]
Hello,

I have xbmc running on a VU+ duo2 stb, which is mips based architecture.

Does acestream/aceproxy work with this set up?

I have everthing set up as per your guide but it just wont connect with the ace engine on my W7 PC.  

This is where i get too but nothing conect s from the box when i try to open a live stream on the box. 

17.01.2015 15:31:14 DEBUG INIT: Plugin loaded: P2pproxy
17.01.2015 15:31:14 DEBUG INIT: Plugin loaded: Stat
17.01.2015 15:31:14 DEBUG INIT: Plugin loaded: Torrenttelik
17.01.2015 15:31:14 DEBUG INIT: Plugin loaded: Torrenttv
17.01.2015 15:31:15 DEBUG VlcClient_init: Successfully connected with VLC socket
!
17.01.2015 15:31:15 INFO VlcClient_recvData: Authentication successful
17.01.2015 15:31:25 INFO HTTP: Detected ace port: 58160
17.01.2015 15:31:25 INFO HTTP: Using gevent 1.0.1
17.01.2015 15:31:25 INFO HTTP: Using psutil 2.2.0
17.01.2015 15:31:25 INFO HTTP: Using VLC VLC media player 2.0.8 Twoflower
17.01.2015 15:31:25 INFO HTTP: Server started.

I can see other xbmc from cmd terminal when use http proxy in settings, of course it comes up as error but it shows xbmc & aceproxy can see each other. Its just the aceproxy does not register at all.

I have ace 3.0.2 installed

I have copy the port from aceengine (each time i start up) to the aceconfig.py, i have set the xbmc acestream to my pc's ip address and port 8000. I have opened the ace engine port on my router and also opened 8000 port on it too. 

I can watch torrent.ru streams from google chrome..

I dont know what else to do, i am starting to think mips is the problem..

Hope you can help

**Comment by ValdikSS** [comment]
Hello!
AceProxy should work fine on any architecture. I don't see any requests in
your aceproxy log. Did you try to load any streams via aceproxy?

**Comment by miltador** [comment]
I guess the problem is with your W7 PC. AceStream engine on Windows always bind to another port and it is not possible to change this behavior so far. Use Linux\Android based host for AceStream engine with --bind-all option.

**Comment by jamescraig81** [comment]
Hello ValdikSS 

Yes i attempted to open many many streams via xbmc ace proxy, it hangs for a while the opens enigma2 player and stops. Nothing happens in the aceproxy log. its as if it does not connect. Although i have proven that xbmc can connect with the aceproxy.log using the http proxy in the xbmc setting

*vu+/mips port of xbmc has issues using xbmc media player so uses external player instead. 

Hi miltador

I'm sorry im a novice and dont know how to do either of these thing you mention, yet, but i will try investigate this though! thanks

**Comment by miltador** [comment]
jamescraig81

Press Win + R on your W7 PC, the Run window will popup. Write "cmd" there (w\o quotes) and hit Enter. Command Prompt will popup. Write there the following command:
AppData\Roaming\ACEStream\engine\ace_console.exe --client-wx  --bind-all

**Comment by jamescraig81** [comment]
Thanks for that, it worked but seems to have caused another problem..

Now everytime I attempt to load aceproxy it say that C:\Python27\Python.exe is not a valid win32 application. I have restarted my computer twice tried it with and without ace engine running but still get the error.

**Comment by ValdikSS** [comment]
Try to reinstall python.

**Comment by jamescraig81** [comment]
Ok yeh reinstalled something abt dlls missing..

I used your command and aceengine starts, as i cant use that cmd prompt for starting aceproxy I have too open another and heres what i get:

Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\W7>C:\Python27\Python.exe C:\Python27\aceproxy\acehttp.py
17.01.2015 19:27:54 DEBUG INIT: Plugin loaded: P2pproxy
17.01.2015 19:27:54 DEBUG INIT: Plugin loaded: Stat
17.01.2015 19:27:54 DEBUG INIT: Plugin loaded: Torrenttelik
17.01.2015 19:27:54 DEBUG INIT: Plugin loaded: Torrenttv
17.01.2015 19:27:54 ERROR HTTP: Cannot find VLC!

C:\Users\W7>C:\Python27\Python.exe C:\Python27\aceproxy\acehttp.py
17.01.2015 19:28:29 DEBUG INIT: Plugin loaded: P2pproxy
17.01.2015 19:28:29 DEBUG INIT: Plugin loaded: Stat
17.01.2015 19:28:29 DEBUG INIT: Plugin loaded: Torrenttelik
17.01.2015 19:28:29 DEBUG INIT: Plugin loaded: Torrenttv
17.01.2015 19:28:29 DEBUG VlcClient_init: Successfully connected with VLC socket
!
17.01.2015 19:28:29 INFO VlcClient_recvData: Authentication successful
17.01.2015 19:28:40 ERROR HTTP: Ace Engine is not running!

Although i can see aceengine is running in the other cmd and the sys tray. Think this happened last time than i lost the dlls..

**Comment by jamescraig81** [comment]
Yes thats the dlls missing again, is this an issue with not having visual studios installed?

**Comment by ValdikSS** [comment]
No, it shouldn't be. What is exact error message?

**Comment by jamescraig81** [comment]
ok i've went through the same procedure and have stopped getting the error 'python.exe is not a valid win32 application'

When I run ace engine through cmd with -
AppData\Roaming\ACEStream\engine\ace_console.exe --client-wx --bind-all
Ace engine starts, i can see it in the system tray..

I have to open another cmd to run -
C:\Python27\Python.exe C:\Python27\aceproxy\acehttp.py
Which gives me the following:

C:\Users\W7>C:\Python27\Python.exe C:\Python27\aceproxy\acehttp.py
17.01.2015 19:49:12 DEBUG INIT: Plugin loaded: P2pproxy
17.01.2015 19:49:12 DEBUG INIT: Plugin loaded: Stat
17.01.2015 19:49:12 DEBUG INIT: Plugin loaded: Torrenttelik
17.01.2015 19:49:12 DEBUG INIT: Plugin loaded: Torrenttv
17.01.2015 19:49:12 DEBUG VlcClient_init: Successfully connected with VLC socket
!
17.01.2015 19:49:12 INFO VlcClient_recvData: Authentication successful
17.01.2015 19:49:22 ERROR HTTP: Ace Engine is not running!

This happens in a loop everytime now, with no more errors saying 'python.exe is not a valid win32 application'

I have tried to start the aceengine with a double click and the server starts..

C:\Users\W7>C:\Python27\Python.exe C:\Python27\aceproxy\acehttp.py
17.01.2015 19:51:47 DEBUG INIT: Plugin loaded: P2pproxy
17.01.2015 19:51:47 DEBUG INIT: Plugin loaded: Stat
17.01.2015 19:51:47 DEBUG INIT: Plugin loaded: Torrenttelik
17.01.2015 19:51:47 DEBUG INIT: Plugin loaded: Torrenttv
17.01.2015 19:51:47 DEBUG VlcClient_init: Successfully connected with VLC socket
!
17.01.2015 19:51:47 INFO VlcClient_recvData: Authentication successful
17.01.2015 19:51:58 INFO HTTP: Detected ace port: 51376
17.01.2015 19:51:58 INFO HTTP: Using gevent 1.0.1
17.01.2015 19:51:58 INFO HTTP: Using psutil 2.2.0
17.01.2015 19:51:58 INFO HTTP: Using VLC VLC media player 2.0.8 Twoflower
17.01.2015 19:51:58 INFO HTTP: Server started.

This is where it stops though, theres no connection from xbmc after this point..

**Comment by miltador** [comment]
Try to start aceengine in console mode by this command:
AppData\Roaming\ACEStream\engine\ace_console.exe --client-console --bind-all
Maybe GUI version ignores '--bind-all' argument.

**Comment by jamescraig81** [comment]
Thanks for you help its really appreciated..

Tried that and get this:

C:\Users\W7>AppData\Roaming\ACEStream\engine\ace_console.exe --client-console --
bind-all
2015-01-18 15:13:51,387|MainThread|acestream|platform=win32
2015-01-18 15:13:51,401|MainThread|acestream|app=acestream
2015-01-18 15:13:51,401|MainThread|acestream|version=3.0.2 code=3000200 revision
=1305 date=2014/10/13 12:36:53
2015-01-18 15:13:51,407|MainThread|acestream|use_local_db=True
2015-01-18 15:13:51,407|MainThread|acestream|use_m2crypto=True
2015-01-18 15:13:51,407|MainThread|acestream|enable debug: 0
2015-01-18 15:13:51,407|MainThread|acestream|get_default_api_version: 2
2015-01-18 15:13:55,536|MainThread|acestream.SocketHandler.InterruptSocket|bound
 on 127.0.0.1:58119
2015-01-18 15:13:55,542|MainThread|acestream.SocketHandler.SocketHandler|bind: s
ocket bound: host=0.0.0.0 port=7777
2015-01-18 15:13:55,542|MainThread|acestream.LM|listen on 7777
2015-01-18 15:13:55,607|MainThread|acestream.VideoServer|start: addr= port=6878
2015-01-18 15:13:55,611|MainThread|acestream.VideoServer|start: addr= port=6879
2015-01-18 15:13:55,637|MainThread|acestream.SocketHandler.InterruptSocket|bound
 on 127.0.0.1:58122
2015-01-18 15:13:55,641|MainThread|acestream.SocketHandler.SocketHandler|bind: s
ocket bound: host=0.0.0.0 port=51055
2015-01-18 15:13:55,647|Instance2InstanceThread-27|acestream.APIServer|run: read
y to receive remote commands on 51055

I then have to open another cmd prompt but the engine is still 'not running' (The icon does not appear in the system tray this time):

C:\Users\W7>C:\Python27\Python.exe C:\Python27\aceproxy\acehttp.py
18.01.2015 15:15:30 DEBUG INIT: Plugin loaded: P2pproxy
18.01.2015 15:15:30 DEBUG INIT: Plugin loaded: Stat
18.01.2015 15:15:30 DEBUG INIT: Plugin loaded: Torrenttelik
18.01.2015 15:15:30 DEBUG INIT: Plugin loaded: Torrenttv
18.01.2015 15:15:30 DEBUG VlcClient_init: Successfully connected with VLC socket
!
18.01.2015 15:15:30 INFO VlcClient_recvData: Authentication successful
18.01.2015 15:15:40 ERROR HTTP: Ace Engine is not running!

I have began installing acestream into ubuntu as you advised in earlier post. It would be much better if this was working in W7 though..

**Comment by jamescraig81** [comment]
This can be closed, it works fine. I had left a CMD in the P2P-streams addon config, even though it was set to default and was greayed out when chose your proxy it still reads that and thats why I did not connect with the PC. I 'accidently' moved all setting to default and everything works fine. Thanks for you both for all your help..!

**Comment by ValdikSS** [comment]
Great!
