### ISSUE TITLE
More detailed instructions

### ISSUE THREAD

**Issue by brimur** [ValdikSS/aceproxy#30]
Hi I followed your instructions but I get stuck at the bottom when I try to get things running. You suggest starting VLC and Acestream engine but Im confused. Which command is used to start Acestream. There are many options. Is it one of these below? 
Also when I start VLC using your commands it does not allow me to do anything else so I cannot then start the proxy. Is there a way to start VLC as a daemon instead? Thanks  

````
usage: acestreamengine
[--client-console | --client-wx | --client-gtk | --stream-source-node | --stream-support-node | --stream-startup-node | --create-transport | --create-transport-multi | --start-tracker | --get-infohash PATH |-get-file-info PATH | --get-file-info-with-id PATH | -v]
````

**Comment by ValdikSS** [comment]
AceStream Engine could be ran from console (--client-console) or with GUI (with the shortcut or --client-wx). VLC doesn't support daemon mode AFAIK, but you can use any available method to do so (aceproxy spawn / your init system / anything else).

**Comment by deseven** [comment]
If you don't want to use the internal spawning procedures the basic way to start VLC as a daemon (in background) is to use ```screen```, like that:
```screen -dmS vlc "/usr/bin/vlc -I telnet --clock-jitter 0 --network-caching 500 --sout-mux-caching 500 --telnet-password admin --telnet-port 4212"```

**Comment by brimur** [comment]
Thanks for the info. Can I get acestream and aceproxy to start in init.d?

**Comment by ValdikSS** [comment]
There is systemd services for acestream (from ArchLinux PKGBUILD) and aceproxy (in this repo). Other init systems are not supported, but you can write init script and do a pull request.
