### ISSUE TITLE
Aceproxy not work?

### ISSUE THREAD

**Issue by marian3** [ValdikSS/aceproxy#31]
Hello, already with desperately. Where do I find a error?

<pre><code>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.10
Release:	14.10
Codename:	utopic

acestreamengine -v
version: 3.0.3 revision: 1355M

sudo acestreamengine --stream-source --name "stv1" --title "stv1" --source "http://192.168.0.19:4242/bysid/3001" --bitrate 300000 --publish-dir "/var/www/html/" --cache "/tmp/" --quality SD --category sport
/usr/lib/python2.7/dist-packages/pkg_resources.py:1049: UserWarning: /home/marian/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
2015-05-24 16:25:03,275|MainThread|acestream|enable debug: 0
2015-05-24 16:25:03,360|MainThread|acestream.SocketHandler.InterruptSocket|bound on 127.0.0.1:41591
2015-05-24 16:25:03,361|MainThread|acestream.SocketHandler.SocketHandler|bind: socket bound: host=0.0.0.0 port=7764
2015-05-24 16:25:03,362|MainThread|acestream.LM|listen on 7764
2015-05-24 16:25:03,427|MainThread|acestream.InfiniteHTTPStream|open stream: url=http://192.168.0.19:4242/bysid/3001 reader=builtin thread=MainThread
2015-05-24 16:25:03,451|AceStreamCoreThread|acestream.Live.Storage|__init__: type=disk size=209715200 overflow=5242880 dir=/tmp/ piecelen=262144 chunklen=16384 chunks_per_piece=16 delete_pieces_before_playback=0
2015-05-24 16:25:03,452|AceStreamCoreThread|acestream.StorageEngineDisk|cache path: /tmp/tmpD3e29g
2015-05-24 16:25:03,456|VideoSourceThread-17|acestream.videosource|started input thread
2015-05-24 16:25:03,476|MainThread|acestream.streamer|private node: 0
2015-05-24 16:25:03,477|MainThread|acestream.streamer|trackers: ['http://192.168.0.19:7764/announce']
2015-05-24 16:25:03,477|MainThread|acestream.streamer|metatrackers: []
2015-05-24 16:25:03,478|MainThread|acestream.streamer|bitrate: 300000
2015-05-24 16:25:03,478|MainThread|acestream.streamer|piece size: 262144
2015-05-24 16:25:03,478|MainThread|acestream.streamer|chunk size: 16384
2015-05-24 16:25:03,479|MainThread|acestream.streamer|publish dir: /var/www/html/
2015-05-24 16:25:03,479|MainThread|acestream.streamer|cache dir: /tmp/
2015-05-24 16:25:05,405|Thread-14|acestream.upnp|Unable to create Port Forward. Error:Action Failed
</code></pre>
As assembled acestream played on WIN7 it is ok-http://192.168.0.19/stv1.acelive

run aceproxy(locally acestreamengine --source..) 
<pre><code>
./acehttp.py
24.05.2015 16:23:22 DEBUG INIT: Plugin loaded: Stat
24.05.2015 16:23:22 DEBUG VlcClient_init: Successfully connected with VLC socket!
24.05.2015 16:23:22 INFO VlcClient_recvData: Authentication successful
24.05.2015 16:23:24 INFO HTTP: Ace Stream spawned with pid 5816
24.05.2015 16:23:24 INFO HTTP: Using gevent 1.0
24.05.2015 16:23:24 INFO HTTP: Using psutil 2.1.1
24.05.2015 16:23:24 INFO HTTP: Using VLC VLC media player 2.2.0 Weatherwax
24.05.2015 16:23:24 INFO HTTP: Server started.</code></pre>
but here my effort ends.
I do not know how to actually open the stream.For example:
<code>http://127.0.0.1:8082/192.168.0.19/stv1.acelive</code> 
and variations ends
<pre><code>
24.05.2015 16:23:24 INFO HTTP: Using VLC VLC media player 2.2.0 Weatherwax
24.05.2015 16:23:24 INFO HTTP: Server started.
24.05.2015 16:34:45 INFO http_HTTPHandler: Accepted connection from 127.0.0.1 path /192.168.0.19/stv1.acelive
24.05.2015 16:34:45 WARNING root: Dying with error
127.0.0.1 - - [24/May/2015 16:34:45] code 400, message Bad Request
127.0.0.1 - - [24/May/2015 16:34:45] "GET /192.168.0.19/stv1.acelive HTTP/1.1" 400 -
</code></pre>
<code>http://127.0.0.1:8082/stat</code> 
its ok.

Where to look for errors?
|Thread-14|acestream.upnp|Unable to create Port Forward. Error:Action Failed    ???
24.05.2015 16:23:24 INFO HTTP: Using psutil 2.1.1    ???
in the process of opening the stream?   ???
or?

**Comment by deseven** [comment]
As stated in the aceproxy config you can enable acestream logging by adding ```--log-file filepath``` to the ```acecmd``` var.
I don't understand what you're trying to achieve, i checked ```acestreamengine --help``` and there are no options such as ```--stream-source``` or ```--bitrate```.

**Comment by marian3** [comment]
I do not know why it is not the help, but that creates .acelive stream-version which I.
The log is nothing special.After initialization, there have not change anything.

**Comment by marian3** [comment]
"GET /192.168.0.19/stv1.acelive HTTP/1.1" 400
slash at the beginning is about problem.
There is another way of opening .acelive stream?

**Comment by ValdikSS** [comment]
Please read project's wiki intently. You should open stream as follows:
`http://127.0.0.1:8082/torrent/http%3A%2F%2F127.0.0.1%2Fstv1.acelive`

Also there are some bugs with latest VLC versions, use 2.1.5 or disable it in aceproxy configuration.

**Comment by marian3** [comment]
Thanks.But not work.
Vlc would far out of it, because it is clear that the sending request on aceproxy nothing happens.
I'm no expert extra, but it is possible that the aceproxy can not get to .acelive file?
If I start(linux) the browser eg "/192.168.0.19/stv1.acelive" the effort to download files that does not exist. The windows do not - there is still an IP address ...
It can not be the problem that to run it locally?
For example, if I run the first acestreamengine --stream-surce ... so aceclient aceproxy will not start. The procedure must be reversed. Also if I run acestreamengine --client-console itself, so it can not detect aceproxy.
It's alchimie.
Sorry for my English.

**Comment by ValdikSS** [comment]
I'm not sure if AceStream allows you to run it's node and client on the same PC. I never streamed myself.

By the way, I used port 8082 in that example. I thought you changed port in aceconfig. If you didn't change it, try this link:

`http://127.0.0.1:8000/torrent/http%3A%2F%2F127.0.0.1%2Fstv1.acelive`

**Comment by marian3** [comment]
Port is ok, changed it.
I try to configure it for different machines and I'll know (although yesterday I already did, but still not very understand it).
It could not be the source code modified to aceproxy sought .acelive at 192.168 .... and not /192.168 ..... Even though I do not know how it actually is.

**Comment by ValdikSS** [comment]
Sorry, I can't understand you.
So, let's make things clear. You have AceStream in streaming mode and you want to run AceProxy on the same computer. What's in AceProxy log when you try to open the following URL in browser or video player?

`http://127.0.0.1:8082/torrent/http%3A%2F%2F192.168.0.19%2Fstv1.acelive`

**Comment by marian3** [comment]
Remote PC
<pre><code>lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

acestreamengine -v
version: 3.0.2 revision: 1323
</code></pre>
<pre><code>./acehttp.py 
24.05.2015 22:28:36 DEBUG INIT: Plugin loaded: Stat
24.05.2015 22:28:36 DEBUG INIT: Plugin loaded: P2pproxy
24.05.2015 22:28:36 DEBUG INIT: Plugin loaded: Torrenttv
24.05.2015 22:28:36 DEBUG INIT: Plugin loaded: Torrenttelik
24.05.2015 22:28:36 DEBUG VlcClient_init: Successfully connected with VLC socket!
24.05.2015 22:28:36 INFO VlcClient_recvData: Authentication successful
24.05.2015 22:28:37 INFO HTTP: Ace Stream spawned with pid 1659
24.05.2015 22:28:37 INFO HTTP: Using gevent 1.0.1
24.05.2015 22:28:37 INFO HTTP: Using psutil 2.1.1
24.05.2015 22:28:37 INFO HTTP: Using VLC VLC media player 2.2.0-rc2 Weatherwax
24.05.2015 22:28:37 INFO HTTP: Server started.
24.05.2015 22:29:21 INFO http_HTTPHandler: Accepted connection from 127.0.0.1 path /torrent/http%3A%2F%2F192.168.0.19%2Fstv1.acelive
24.05.2015 22:29:21 ERROR HTTP: Request seems like valid but no valid video extension was provided
24.05.2015 22:29:21 WARNING root: Dying with error
127.0.0.1 - - [24/May/2015 22:29:21] code 400, message Bad Request
127.0.0.1 - - [24/May/2015 22:29:21] "GET /torrent/http%3A%2F%2F192.168.0.19%2Fstv1.acelive HTTP/1.1" 400 -
24.05.2015 22:29:21 INFO http_HTTPHandler: Accepted connection from 127.0.0.1 path /torrent/http%3A%2F%2F192.168.0.19%2Fstv1.acelive
24.05.2015 22:29:21 ERROR HTTP: Request seems like valid but no valid video extension was provided
24.05.2015 22:29:21 WARNING root: Dying with error
127.0.0.1 - - [24/May/2015 22:29:21] code 400, message Bad Request
127.0.0.1 - - [24/May/2015 22:29:21] "GET /torrent/http%3A%2F%2F192.168.0.19%2Fstv1.acelive HTTP/1.0" 400 -
</code></pre>
If anything test so far can I do it on one machine

**Comment by ValdikSS** [comment]
Oh sorry. Try this:
`http://127.0.0.1:8082/torrent/http%3A%2F%2F192.168.0.19%2Fstv1.acelive/video.mp4`

**Comment by marian3** [comment]
Its ok, thanks.Remote also locale

**Comment by ValdikSS** [comment]
It works?

**Comment by marian3** [comment]
yes
