### ISSUE TITLE
Improve wiki

### ISSUE THREAD

**Issue by Alex0007** [ValdikSS/aceproxy#32]
>Перед запуском прокси, вам необходимо предварительно запустить Ace Stream и VLC с telnet-интерфейсом, если вы его используете.

[Не сказано](https://github.com/ValdikSS/aceproxy/wiki/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B0-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%28Linux%29#%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA), как запустить этот самый Ace Stream

**Comment by thestanislav** [comment]
По идее это есть в файле https://github.com/ValdikSS/aceproxy/blob/master/aceconfig.py#L20
Так же есть установить  acespawn = True то Ace Stream запустится автоматом
