### ISSUE TITLE
BadGateway - ...error(111, 'Connection refused')",)

### ISSUE THREAD

**Issue by Kaimas** [ValdikSS/aceproxy#33]
Hello, 
I try run aceproxy server at Ubuntu 14.04 and it's runs, but I got error:

09.08.2015 11:11:42 INFO http_HTTPHandler: Accepted connection from xxx.xxx.xxx.xxx path /pid/6e746d6c082caa0748ad760f1c5c587d048f1482/stream.mp4
09.08.2015 11:11:42 ERROR HTTP: AceClient create exception: AceException("Socket creation error! Ace is not running? error(111, 'Connection refused')",)
09.08.2015 11:11:42 WARNING root: Dying with error
87.247.111.101 - - [09/Aug/2015 11:11:42] code 502, message Bad Gateway
87.247.111.101 - - [09/Aug/2015 11:11:42] "GET /pid/6e746d6c082caa0748ad760f1c5c587d048f1482/stream.mp4 HTTP/1.0" 502 -
09.08.2015 11:11:42 DEBUG AceClient_destroy: Destroying client...

So maybe you know whats can be wrong?

I was try create server with VLC and without it, but error same.
I try open with VLC 2.2.1 at Windows 7, if it important.

Help me please.

Thanks

**Comment by ValdikSS** [comment]
So, is Ace Stream running?

**Comment by Kaimas** [comment]
Thank You, for fast answer. Yes running (icon near clock). Let me try close it, and it's same error:(

Or sorry, and I don't know about what Ace Stream you're talking?

**Comment by ValdikSS** [comment]
Try to close it and run again, then restart aceproxy.

**Comment by Kaimas** [comment]
Same:( But I start aceproxy at VPS (Ubuntu 14.04) and Ace Stream at Windows 7, where VLC Client. Maybe I somehow need install Ace Stream at VPS?

And maybe I can give you my Skype name, then you can connect to my TeamViewer server and try what's wrong, be faster, maybe try?

**Comment by ValdikSS** [comment]
Ah sure you need to run Ace Stream on your VPS. Please follow the wiki http://wiki.acestream.org/wiki/index.php/AceStream_3.0.0_alpha/en

Sorry but I won't help you with installation as I consider Ace Stream as a virus and point people against it.

**Comment by ikatson** [comment]
@ValdikSS can you please comment more on the "Ace Stream is a virus and you point people against it" issue? Why do you think so? As far as I know it's impossible to use aceproxy without Ace Stream, so how does that attitude relate to aceproxy?

**Comment by ValdikSS** [comment]
@ikatson http://habrahabr.ru/post/260617/#comment_8469939

**Comment by ikatson** [comment]
Thanks. And how about aceproxy then? Aceproxy is not malware, but it requires malware to operate

**Comment by ValdikSS** [comment]
@ikatson yes, exactly. That's why I semi-abandon this project. I'm not interested in it anymore.

**Comment by deseven** [comment]
Well okay, i can help. What's the problem anyway? The ace stream "installation" is very simple and straightforward, since you don't need to build anything.
