### ISSUE TITLE
Torrent-tv Plugin

### ISSUE THREAD

**Issue by Quarx2k** [ValdikSS/aceproxy#36]
Проблема с torrent-tv плагином.  На всех каналах играет музыка из Morrowind и данное изображение http://pix.my/t4icbVMS?1440164830
На p2pProxy плагине таки проблем нет.

**Comment by deseven** [comment]
Это не проблема aceproxy.
При скачивании плейлиста отдается файл с одинаковым айди для всех каналов - a2b1d00bc5ec10aaa8983fe026c2e079803466cb.
При этом через родной AcePlayer который они советуют точно такая же картина.

**Comment by PlintuZz** [comment]
вы уверены что вы используете именно торрент тв плагин? на нем проблем нету, прямо сейчас и уже часа 4 смотрю без проблем.
могу предположить что вы используете торрент телик плагин, на нем да есть проблема с листом торрент телик, точнее в данный момент он отдает пустой лист( предполагаю что из за того что сайт торрент телика продается) плейлист allfon работает без проблем.

**Comment by johnmate** [comment]
Проблема именно с торренттв, плейлист даже напрямую при скачивании на все
каналы один id подставляет. Запустил плагин p2pproxy, заработало)
21 авг. 2015 г. 23:39 пользователь "PlintuZz" <notifications@github.com>
написал:

**Comment by PlintuZz** [comment]
ну тогда это вам на форум а не на гитхаб.
собственно на форуме один человек отписался с такой проблемой как у вас, вот цитата ответа модератора.


Re: Обсуждение работы трансляций ТВ каналов. Вопросы и ответы.
« Ответ #3772 : Август 21, 2015, 14:49:24 »

Цитата: kiss от Август 21, 2015, 13:38:11

    випам выдается один и тот же инфохеш айди на все каналы, глюк? и почему инфо хеш начал выдаваться ? еще вчера был торррент файл acelive
 Пур Иванов

    Global Moderator
    Hero Member
Может ваш плейлист оказался в списке забаненых!?

**Comment by deseven** [comment]
Класс, больше эти чудаки от меня ни копейки не получат.

**Comment by umputun** [comment]
Точно такая же проблема вдруг появилась и у меня. Я им отписал в поддержку, но похоже, что они начали блокировать пользователей aceproxy.

**Comment by PlintuZz** [comment]
ну после ответа модератора вида
"Значит они свои плейлисты используют не по назначению и не персонально."
могу предположить только то что или ваш логин пароль стал достоянием общественности, или от вас было через чур много запросов, например вы потоки заворачивали дальше, на какой нить медиасервер или друзьям, в итоге получалось что с одного айпишника 20 каналов крутят, логично что им не понравится, в любом случае это вопросы уже не к разработчику эйспрокси, а к торрент тв.

**Comment by ValdikSS** [comment]
Закрываю.
