### ISSUE TITLE
Проблемы с подключением к потоку

### ISSUE THREAD

**Issue by kosjak1** [ValdikSS/aceproxy#37]
День добрый! Использую связук aceproxe+torrent-tv, сегодня ни как не хотят запускаться несколько HD каналов. Пробовал получить новые ссылки из playlist'a torrent-tv - ничего не помогает. Если включить acelive файл, через AceStream Player, то все работает. В чем может быть проблема?

Привожу часть лога aceproxy:

28.08.2015 09:42:41 WARNING root: Dying with error
94.242.221.167 - - [28/Aug/2015 09:42:41] code 500, message Internal Server Error
94.242.221.167 - - [28/Aug/2015 09:42:41] "GET /torrent/http%3A%2F%2Fcontent.torrent-tv.ru%2FQk9qaGkya1pKdlFVY3lhRXUvMkdaZTRqemZ3R1Y2TFBXaGlqd0Nqek54MkswR3pZNklsN1lQdmd2TFlFVG95WGVlamtNNXRQZWdVVS9UVmF2VVJDb3c9PQ%2F13110.acelive/stream.mp4 HTTP/1.0" 500 -
28.08.2015 09:42:41 DEBUG HTTP: END REQUEST
28.08.2015 09:42:41 DEBUG HTTP: That was the last client, destroying AceClient
28.08.2015 09:42:41 DEBUG http_hangDetector: Client disconnected
28.08.2015 09:42:41 DEBUG AceClient_recvdata: Got SHUTDOWN from engine
28.08.2015 09:42:41 DEBUG AceClient_recvdata: Got SHUTDOWN from engine
28.08.2015 09:42:41 DEBUG AceClient_recvdata: Got SHUTDOWN from engine
28.08.2015 09:42:41 ERROR VlcClient_recvData: Broadcast does not exist!
28.08.2015 09:42:41 ERROR VlcClient_stopBroadcast: stopBroadcast error
28.08.2015 09:42:41 DEBUG AceClient_destroy: Destroying client...
28.08.2015 09:42:41 ERROR HTTP: Traceback (most recent call last):
  File "./acehttp.py", line 324, in handleRequest
    self.url = self.url.replace('127.0.0.1', AceConfig.acehost)
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by stek29** [comment]
Проблема решена?

**Comment by kosjak1** [comment]
Боюсь, что спустя 5 месяцев - проблема уже не акутальна. Учитывая, что acestream уже сделал решение "из кробоки" для HLS.

**Comment by stek29** [comment]
Так может закрыть тогда issue?
