### ISSUE TITLE
VLC: MPEG-4 descriptor not found

### ISSUE THREAD

**Issue by Kaimas** [ValdikSS/aceproxy#38]
Hello,

I faced with problem when I try open channel at VLC, i use Ubuntu aceproxy.
When I run vlc with telnet and python2 acehttp.py then I try open channel at VLC via proxy I get output (python2 acehttp.py):

18.10.2015 09:56:44 INFO http_HTTPHandler: Accepted connection from xx.xxx.xxx.xxx path /pid/d6bdc8edc8fcc563b1770195e6113626d004f277/stream.mp4
18.10.2015 09:56:44 INFO AceClient_init: Successfully connected with Ace!
18.10.2015 09:56:44 DEBUG HTTP: AceClient created
18.10.2015 09:56:44 DEBUG HTTP: hangDetector spawned
18.10.2015 09:56:44 DEBUG AceClient_aceInit: aceInit ended
18.10.2015 09:56:44 DEBUG HTTP: AceClient inited
18.10.2015 09:56:44 DEBUG AceClient_recvdata: STATUS changed to main:loading
18.10.2015 09:56:44 DEBUG AceClient_recvdata: Content info: {u'status': 1, u'files': [[u'National%20Geographic%20HD', 0]], u'infohash': u'0d6969b6abd25648074c1fc8c375a6b21b245d12', u'checksum': u'48ec7b315ede6d9e7d4b5b7d16e5e33ca6e5ff28'}
18.10.2015 09:56:44 DEBUG HTTP: START done
18.10.2015 09:56:44 DEBUG AceClient_recvdata: STATUS changed to main:idle
18.10.2015 09:56:45 DEBUG AceClient_recvdata: STATUS changed to main:starting
18.10.2015 09:56:46 DEBUG AceClient_recvdata: STATUS changed to main:prebuf
18.10.2015 09:56:46 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:46 DEBUG AceClient_recvdata: Seeking back
18.10.2015 09:56:47 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:47 DEBUG HTTP: Got url http://127.0.0.1:6878/content/0d6969b6abd25648074c1fc8c375a6b21b245d12/0.306337011575
18.10.2015 09:56:47 DEBUG VlcClient_recvData: Broadcast started
18.10.2015 09:56:47 DEBUG VlcClient_startBroadcast: Broadcast started
18.10.2015 09:56:48 DEBUG HTTP: VLC url http://127.0.0.1:8081/d6bdc8edc8fcc563b1770195e6113626d004f277
xx.xxx.xxx.xxx - - [18/Oct/2015 09:56:48] "GET /pid/d6bdc8edc8fcc563b1770195e6113626d004f277/stream.mp4 HTTP/1.1" 200 -
18.10.2015 09:56:48 DEBUG HTTP: Headers sent
18.10.2015 09:56:48 DEBUG http_proxyReadWrite: Started
18.10.2015 09:56:48 DEBUG AceClient_recvdata: STATUS changed to main:dl
18.10.2015 09:56:48 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:49 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:50 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:51 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:52 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:53 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:54 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:55 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:56 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:57 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:58 WARNING http_proxyReadWrite: Video connection closed
18.10.2015 09:56:58 DEBUG http_hangDetector: Client disconnected
18.10.2015 09:56:58 DEBUG HTTP: END REQUEST
18.10.2015 09:56:58 DEBUG HTTP: Sleeping for 3 seconds
18.10.2015 09:56:58 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:56:59 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:57:00 DEBUG AceClient_recvdata: Current position/last/buf: 100/100/10
18.10.2015 09:57:01 DEBUG HTTP: That was the last client, destroying AceClient
18.10.2015 09:57:01 DEBUG VlcClient_recvData: Broadcast stopped
18.10.2015 09:57:01 DEBUG VlcClient_stopBroadcast: Broadcast stopped
18.10.2015 09:57:01 DEBUG AceClient_destroy: Destroying client...
18.10.2015 09:57:01 DEBUG AceClient_recvdata: Got SHUTDOWN from engine

AND I get error at VLC at Ubuntu:

[0x7fcbf000e548] [Media: d6bdc8edc8fcc563b1770195e6113626d004f277] ts demux error: MPEG-4 descriptor not found

Channel not plays:(

Maybe you know what's can be wrong?

Thanks

**Comment by ValdikSS** [comment]
Do you have outdated AceEngine? Try to disable seekback.

**Comment by Kaimas** [comment]
Can be that outdate AceEngine, because I about two months don't use it and after it it's not works.. So I try on new VPS install all and it's works, so it's probably outdated.

Thank You for your answer, If I faced with new problem I write here, until
