### ISSUE TITLE
Torrent-TV

### ISSUE THREAD

**Issue by nsoq** [ValdikSS/aceproxy#47]
В конфиге указал ссылку на плейлист, но при получении плейлиста с прокси, то получается такая ошибка:
Error response
Error code 500.
Message: Internal Server Error.
Error code explanation: 500 = Server got itself in trouble.
Плагин Torrent-TV

**Comment by ValdikSS** [comment]
Проект заброшен, пожалуйста, разбирайтесь сами.

**Comment by nsoq** [comment]
Жалко.. ничего в этом не понимаю

**Comment by vhsw** [comment]
@nsoq немного слоу, но тем не менее, в plugins/config/torrenttv.py нужно указать url, к примеру url = 'https://pomoyka.lib.emergate.net/trash/ttv-list/ace.all.player.m3u' или любой другой ace-плейлист
